### ISSUE TITLE
Not all the IP's detected .

### ISSUE THREAD

**Issue by reznov11** [milo2012/metasploitHelper#12]
I have more than one computer connected to my wifi, for the first time if i chose any of the options , i can't get all the computers into the list, if i tried twice or more, then i get them all, please can you fix this issue .

**Comment by milo2012** [comment]
Can you send me a screen dump ?
Are the firewall enabled on the computers ?


On Jan 22, 2017 1:29 AM, "Reznov Ammar" <notifications@github.com> wrote:

I have more than one computer connected to my wifi, for the first time if i
chose any of the options , i can't get all the computers in the list, if i
tried twice maybe more, then i get them all, please can you fix this issue .

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/milo2012/metasploitHelper/issues/12>, or mute the thread

**Comment by reznov11** [comment]
Here i have 5 hosts up:
https://s27.postimg.org/lq7v1dxdf/image.png

And here showing just 4, you can say the gateway is not included:
https://s30.postimg.org/pish5qttd/image.png

**Comment by milo2012** [comment]
Sorry the screenshot doesn't show my tool.
